server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user2024
    username: ${USER_DB}
    password: ${PASS_DB}
jpa:
  database-platform: org.hibernate.dialect.MySQLDialect
  hibernate:
    ddl-auto: update
jwt:
  secret: ${SECRET_KEY}